apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nvpj2u1o0-go 
  janus-idp.io/tekton: nvpj2u1o0-go
  backstage.io/kubernetes-id: nvpj2u1o0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nvpj2u1o0-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  